### ISSUE TITLE
Required Rhino wacky

### ISSUE THREAD

**Issue by IamStig** [KubeJS-Mods/Rhino#1]
Um, 12 was greater than 11 when I went to scool (sic)
My guess is the "-build" is causing a problem

Edit - sorry forgot this info 
MC version 1.16.5
Forge 36.0.1
kubejs-1605.3.5-build.155-forge
rhino-1.7.13-build.12

![image](https://user-images.githubusercontent.com/20489424/106211083-2be58300-621c-11eb-87b7-102d35975447.png)

**Comment by Furious1964** [comment]
Might be the new Common Core Math they're using.

**Comment by LatvianModder** [comment]
Should be fixed by now
