### ISSUE TITLE
Crash when loading game with rhino-forge-1801.1.8-build.99

### ISSUE THREAD

**Issue by isaaclepes** [KubeJS-Mods/Rhino#11]
I was having an issue where KubeJS would crash the game when added to the mods folder. I posted incorrectly to KubeJS ( see https://github.com/KubeJS-Mods/KubeJS/issues/268) where I was told it was not the same issue and to upgrade Rhino, so I tried the beta build of Rhino. Instead of crashing immediately, it crashes on the Mojang logo screen.

The game crashed whilst exception in server tick loop
Error: java.util.concurrent.CompletionException: net.minecraft.ReportedException: Accessing PalettedContainer from multiple threads
Exit Code: -1

Crash log: https://gist.github.com/isaaclepes/101552a456b1eff0ba5e03c4b7f63f88
Debug Log:  https://gist.github.com/isaaclepes/cdf6d0e3df44628746735cf86484e5cd
latest log: https://gist.github.com/isaaclepes/e5f1396f653d1050afc1f24245dcbd73

If I remove kubejs and revert to Rhino build 94, the crashes stop.

**Comment by isaaclepes** [comment]
Closing issue ticket:  The correlation was not causation, I was just able to reproduce the crash with build 94.  Apparently it intermittently works, which gave the appearance it worked only when Rhino was on build 94.

**Comment by MaxNeedsSnacks** [comment]
For reference, this issue seems to be related to FerriteCore, and perhaps some bad interaction of FerriteCore with Refined Storage. Also, generally speaking, KubeJS *should* error out if the version of rhino is too low; I'm guessing that didn't happen this time because we forgot to update the mod info files

**Comment by isaaclepes** [comment]
Thanks.  I also found an issue on their tracker that matches:
https://github.com/malte0811/FerriteCore/issues/52
