### ISSUE TITLE
File Names Incorrect on Curseforge

### ISSUE THREAD

**Issue by SurprisedPikaa** [KubeJS-Mods/Rhino#15]
Very small issue, but the file names for 1.18.2 releases on Curse still have "1801" in them, rather than "1802". I realised this was a mistake, but others could take this to mean that Rhino is not yet updated to 1.18.2.
![image](https://user-images.githubusercontent.com/82579156/163729942-bbf3d3b5-ca55-4ded-ab89-07e4abffc695.png)

**Comment by MaxNeedsSnacks** [comment]
This is not an issue, we still compile against 1.18.1 for Rhino (tho that'll change pretty soon now that Kube 1.18.2 is out and the general modded consensus is that 1.18.1 is dead)
