### ISSUE TITLE
Incompatibilities due to FabricLauncherBase (e.g. Quilt)

### ISSUE THREAD

**Issue by sisby-folk** [KubeJS-Mods/Rhino#16]
I don't have a solid solution for this one, but I thought I'd make it visible in case anyone gets ambitious.

Using `net.fabricmc.loader.impl.launch.FabricLauncherBase` in `FabricRemapper` (Import [FabricRemapper.java#6](https://github.com/KubeJS-Mods/Rhino/blob/67d9e61eb7270c41ace7aa0d99f3db6a894a5874/fabric/src/main/java/dev/latvian/mods/rhino/mod/util/fabric/FabricRemapper.java#L6), usages [FabricRemapper.java#34](https://github.com/KubeJS-Mods/Rhino/blob/67d9e61eb7270c41ace7aa0d99f3db6a894a5874/fabric/src/main/java/dev/latvian/mods/rhino/mod/util/fabric/FabricRemapper.java#34) [FabricRemapper.java#38](https://github.com/KubeJS-Mods/Rhino/blob/67d9e61eb7270c41ace7aa0d99f3db6a894a5874/fabric/src/main/java/dev/latvian/mods/rhino/mod/util/fabric/FabricRemapper.java#L38) [FabricRemapper.java#41](https://github.com/KubeJS-Mods/Rhino/blob/67d9e61eb7270c41ace7aa0d99f3db6a894a5874/fabric/src/main/java/dev/latvian/mods/rhino/mod/util/fabric/FabricRemapper.java#L41)) causes Rhino to fail without fabric loader even when a drop-in replacement for FAPI's interfaces ([QSL](https://github.com/QuiltMC/quilt-standard-libraries)) is provided.

[Sample crash log](https://0x0.st/oAkB.txt)

It's used as the source of the mappings in use, so there'd need to be a whole usable replacement for getting those. No idea - But I might as well make it known and toss it out to the quilt team/community to see if they have anything useful.

**Comment by LatvianModder** [comment]
I guess ill just disable remapping if there's no FabricLoader class for now

**Comment by LatvianModder** [comment]
This should be fixed now, re-open if it's still an issue
