### ISSUE TITLE
Crashing at start of client

### ISSUE THREAD

**Issue by TheButterbrotMan** [KubeJS-Mods/Rhino#17]
Minecraft: 1.18.2
Fabric: 0.13.3
https://bytebin.lucko.me/dOVMasieac

**Comment by MaxNeedsSnacks** [comment]
Your version of KubeJS is severely out of date and relies on Rhino features that were removed in the latest update (that I'll have to yell at Lat about if he didn't at least do a version bump or anything to *indicate any sort of breakage*), please update to the latest JAR available ^^

**Comment by MaxNeedsSnacks** [comment]
You're still on an old version, 403 is the latest build out there and should work with this version of Rhino
