### ISSUE TITLE
Rhino-fabric-1802.1.11-build.165 crashes on startup

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [KubeJS-Mods/Rhino#18]
**MC** 1.18.2
**Fabric loader** 0.14.5
**Rhino** 1802.1.11-build.165

Reverting back to 1802.1.10-build.155 fixes the issue.

Logs: https://gist.github.com/Footage2-Amply-Pounce/d14e067570704a30caa8a1fc5095f1a5

**Comment by MaxNeedsSnacks** [comment]
A new version should be out to fix this
