### ISSUE TITLE
includes does not work with KubeJS Java strings

### ISSUE THREAD

**Issue by TheQKnight** [KubeJS-Mods/Rhino#28]
### Minecraft Version

1.18.2

### KubeJS Version

kubejs-fabric-1802.5.1-build.386.jar

### Rhino Version

rhino-fabric-1801.1.9-build.135.jar

### Architectury Version

architectury-4.4.54.jar

### Forge/Fabric Version

fabric-1801.1.9-build.135

### Describe your issue

![unknown](https://user-images.githubusercontent.com/17223871/167241609-54e0b5ba-2e81-4d06-94bb-4c052285f939.png)
![unknown](https://user-images.githubusercontent.com/17223871/167241611-4557bb1e-58e5-48c3-b278-ab621ab72ab2.png)

When using includes from a generated string, such as an id from a block, it does not behave properly

**Comment by MaxNeedsSnacks** [comment]
Can you check if the issue persists after [this commit](https://github.com/KubeJS-Mods/Rhino/commit/3c5efa13edb5eb01bd7299bfb3965d46da5760ef)? The accompanying dev build would be [this file](https://mvn.saps.dev/minecraft/dev/latvian/mods/rhino-fabric/1802.1.14-build.196/rhino-fabric-1802.1.14-build.196.jar)

**Comment by ChiefArug** [comment]
It does not fix it

**Comment by MaxNeedsSnacks** [comment]
https://github.com/KubeJS-Mods/Rhino/commit/855f4257513e2557408d86727eabb76cd0ab2d7e on the other hand, should've fixed it (confirmed by a tester)
