### ISSUE TITLE
Rhino curse compatibility

### ISSUE THREAD

**Issue by jclendineng** [KubeJS-Mods/Rhino#3]
I am on MC 1.16.5, latest version of Forge. Rhino 1.17.13 Build 14 is the latest I can download through Curse, when I download the latest (and only compatible version for KubeJS) version through the curse website, the app states that it has been removed from Curse and will only work with legacy modpacks.

**Comment by callmejay758** [comment]
Can confirm its happening with me too, its really annoying to update all my mods and then have to reupdate this mod separately.

**Comment by MaxNeedsSnacks** [comment]
Fixed by https://github.com/KubeJS-Mods/Rhino/commit/98dade93b2fe23ea48531edf18c89488c2dcf0ec (I can't believe that worked)
