### ISSUE TITLE
Is it normal for rhino to be using quite a lot of resources?

### ISSUE THREAD

**Issue by Foxydapirate12** [KubeJS-Mods/Rhino#30]
I checked the Spark Heap summary and Rhino was the first mod to show up in the list as the list is sorted from highest to lowest thing using resources, this is what the listing stated: 
Instances: 2,158, Size: 151.7 KB, Type: dev.latvian.mods.rhino.NativeJavaMethod.
If needed I could provide a link to the heap summary
Also this was on 1.18.2 Forge version 40.1.69
![image](https://user-images.githubusercontent.com/101042481/182784270-bac958f2-5d46-48cf-be7e-1bc17e2c1a14.png)

**Comment by LatvianModder** [comment]
That's normal. The memory usage might be lower after a Rhino rewrite I'm working on, but it has to keep track of all methods in all classes for scripts to use them, there's just no other way. Plus its... 150 kilobytes. If your computer is from this millennia, it should be fine.
