### ISSUE TITLE
The 1.21 version still mark fabric as compatible

### ISSUE THREAD

**Issue by lzm11111111** [KubeJS-Mods/Rhino#48]
Despite fabric support have been dropped. However, in the curseforge and modrinth it still mark fabric as compatible

**Comment by LatvianModder** [comment]
There are no fabric versions of 1.21 or 1.21.1 🤔 https://www.curseforge.com/minecraft/mc-mods/kubejs/files/all?page=1&pageSize=20&version=1.21&gameVersionTypeId=4

**Comment by lzm11111111** [comment]
> There are no fabric versions of 1.21 or 1.21.1 🤔 https://www.curseforge.com/minecraft/mc-mods/kubejs/files/all?page=1&pageSize=20&version=1.21&gameVersionTypeId=4

I means this
![whats](https://github.com/user-attachments/assets/6e802b06-df2b-4f1c-9d78-e9c4c694defe)

**Comment by LatvianModder** [comment]
Oh, well rhino the javascript engine is compatible, yeah, its just that there's no KubeJS
