### ISSUE TITLE
Latest Rhino and KubeJS update caused Botany Pots script to fail

### ISSUE THREAD

**Issue by GalaxySynth** [KubeJS-Mods/Rhino#5]
Relevant line in debug.log

`[11Jun2021 23:57:34.304] [Worker-Main-8/WARN] [KubeJS Server/]: Error creating recipe kubejs:botany_pots/crop/mystical_agriculture/unobtainium[botanypots:crop]: {"seed":{"item":"mysticalagriculture:unobtainium_seeds"},"categories":["insanium"],"growthTicks":5000.0,"display":{"block":"mysticalagriculture:unobtainium_crop","properties":{"age":7.0}},"results":[{"chance":0.75,"minRolls":1,"maxRolls":3,"output":{"item":"mysticalagriculture:unobtainium_essence","count":1}},{"chance":0.03,"minRolls":1,"maxRolls":1,"output":{"item":"mysticalagriculture:unobtainium_seeds","count":1}},{"chance":0.03,"minRolls":1,"maxRolls":1,"output":{"item":"mysticalagriculture:fertilized_essence","count":1}}],"type":"botanypots:crop"}: com.google.gson.JsonSyntaxException: The property age with value 7.0 coul not be parsed!`

[debug.log](https://github.com/KubeJS-Mods/Rhino/files/6641424/debug.log)

KubeJS script that worked with previous versions:

[botany_pots - Copy.txt](https://github.com/KubeJS-Mods/Rhino/files/6641434/botany_pots.-.Copy.txt)

Reverting Rhino to 1.7.13-build.23 fixes the issue

**Comment by GalaxySynth** [comment]
There's also the strange fact that the newest version is flagged for 1.17 but is installable on a 1.16.5 instance via the app, which may have something to do with my issue, PEBKAC?

**Comment by MaxNeedsSnacks** [comment]
> There's also the strange fact that the newest version is flagged for 1.17 but is installable on a 1.16.5 instance via the app, which may have something to do with my issue, PEBKAC?

The new version technically works on every Minecraft since 1.14, but CurseForge doesn’t usually „do“ library dependencies so we need to manually tag them for each version. For pretty much the same reason, newer Rhino builds show up as Fabric only as well, despite supporting any loader

**Comment by GalaxySynth** [comment]
Ah thank you, I thought I was having a dumb moment with this bug report

**Comment by MaxNeedsSnacks** [comment]
The number parsing should be fixed in the latest KubeJS release ^^
