### ISSUE TITLE
latest version not compatible with kubejs

### ISSUE THREAD

**Issue by red2blue** [KubeJS-Mods/Rhino#7]
Kube is saying it requires 

![image](https://user-images.githubusercontent.com/35115304/131610019-607d7c59-ab5e-42bf-a379-359db9047373.png)

**Comment by MaxNeedsSnacks** [comment]
Are you using an old version of KubeJS by any chance? Haven't gotten any reports about this elsewhere

**Comment by red2blue** [comment]
I have the only version you have on curseforge. the one from June. 

now your latest Rhino gives me a message saying its for Minecraft 1.16.4 only
