### ISSUE TITLE
Incorrect Minecraft Version

### ISSUE THREAD

**Issue by Skid-Inc** [KubeJS-Mods/Rhino#8]
Selecting the most recent 1.17.1 build on GDLauncher throws an error on launch that it's the wrong minecraft version. I've manually downloading the same file directly from cruseforge and I get the same error.

![image](https://user-images.githubusercontent.com/8793802/133450062-031f9a19-6cec-4157-a513-e7c5dcb5dabd.png)
![image](https://user-images.githubusercontent.com/8793802/133450099-a3ffd249-b95f-4bf9-80e0-bde984f5fc37.png)

**Comment by Zarepheth** [comment]
Manually changing the required Minecraft version in the `fabric.mod.json` file to "1.17.1" got it working for me. Although, the next time I upgrade/install the mod and use it for MC 1.17.x, it will likely fail -- unless I manually fix it again.

**Comment by red2blue** [comment]
![image](https://user-images.githubusercontent.com/35115304/134264727-63563a59-fe80-40cc-8f28-a54a970d32fb.png)

**Comment by Zarepheth** [comment]
@red2blue To manually fix:

1. Open the `mods` folder for your Minecraft install.
2. Find the `rhino-fabric-*.jar` file.
3. Open that `*.jar` file with a Zip file tool.
4. Find the `fabric.mod.json` file within the archive/jar.
5. Locate the line:
```json
		"minecraft": "~1.16.4",
```
9. Change "~1.16.4" to "~1.17.1"
10. Save the change to the `fabric.mod.json` file.
11. Save the change to the `*.jar` file.

Notes:
- The location of the "mods" folder depends upon the MineCraft installation and how MineCraft is being started. Using CurseForge on OverWolf for Windows, each profile gets its own copy of the "mods" folder. (_Mine is located at `C:\Users\{my-login}\Documents\Curse\Minecraft\Instances\Valhelsia Fabric - 1.17\mods`._)
- `*.jar` files are just Zip files. If you lack a good Zip file tool, you can append `.zip` to the file name and open directly with the Windows explorer. However, Windows does not allow editing of files within zip archives, so you'll have to extract the whole Jar file into its own folder. Then edit the `fabric.mod.json` file and recompress to a zip archive. After which, you'll have to ensure the correct file name and location. (_It is much easier to just get the free version of 7-Zip! Which is the tool I used._)
- You have to go through this hassle, every time the mod is updated (or replaced) - until the mod authors fix the bug.
